# Generated by Django 5.1.6 on 2025-04-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='hotel',
            new_name='room_name',
        ),
    ]
