# Generated by Django 5.2 on 2025-04-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_hotel_reservation_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
