# Generated by Django 5.1.6 on 2025-04-11 14:51

# accounts/migrations/0002_profile_email.py
from django.db import migrations, models # type: ignore

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, blank=True),
        ),
    ]
