# Generated by Django 5.2 on 2025-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_profile_phone_profile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_verified",
            new_name="email_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="verification_code",
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
