# Generated by Django 5.2 on 2025-05-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="profile",
            name="login_otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
