# Generated by Django 5.2 on 2025-05-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_profile_is_verified_profile_login_otp_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="login_otp_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="otp_created_at",
        ),
    ]
