# Generated by Django 5.2 on 2025-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_profile_login_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="login_otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
