# Generated by Django 5.2 on 2025-05-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_profile_login_otp_code_profile_otp_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="login_otp_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="otp_created_at",
        ),
    ]
