# Generated by Django 5.2 on 2025-05-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_profile_email_verification_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_email_verified",
            new_name="email_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="otp_created_at",
        ),
        migrations.AlterField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
