# Generated by Django 5.2 on 2025-05-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_profile_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
    ]
