# Generated by Django 5.2 on 2025-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_profile_is_verified_profile_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="verification_token",
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
