# Generated by Django 5.2 on 2025-05-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_profile_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
    ]
