# Generated by Django 5.2 on 2025-05-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_profile_email_token_profile_is_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_verified",
            new_name="email_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_token",
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
