# Generated by Django 5.2 on 2025-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_rename_is_verified_profile_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
