# Generated by Django 5.2 on 2025-05-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_profile_email_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_verified",
        ),
    ]
