# Generated by Django 5.2 on 2025-05-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_remove_profile_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
