# Generated by Django 5.2 on 2025-05-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0031_remove_otp_user_profile_email_verification_sent_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_sent_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="otp_expiry",
        ),
    ]
