# Generated by Django 5.2 on 2025-05-12 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_profile_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_sent_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email_verification_token",
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
