# Generated by Django 5.2 on 2025-05-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_remove_profile_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="verification_token",
        ),
    ]
